### PR TITLE
update attributes to Lineage v21 wiki state

### PR DESCRIPTION
**Pull request by mobilsicher**
thanks for your parser. I added some attributes to make parsing possible witih the latest wiki state. Admittedly I do skip some attributes, but this should be as before.

### CODE REVIEW

**Comment by chriscamacho** [comment]
to be honest I've not used this in some time, I'll take a look at this PR over the weekend - assuming I get some time !!

**Comment by mobilsicher** [comment]
don't worry if you don't find time on the weekend. Often when using a repo and I run into difficulties I check for open PRs.

**Comment by chriscamacho** [comment]
@mobilsicher I'm not using this and don't have a massive amount for free time for it would you like to take over ownership of this repo ?

**Comment by mobilsicher** [comment]
sure, can do

**Comment by chriscamacho** [comment]
Merge in prep for transfer

**Comment by chriscamacho** [comment]
Unable to transfer just yet as...  mobilsicher/lineageos-device-sql already exists I have merged your pr let me know when you have deleted your fork and I'll transfer...

**Comment by mobilsicher** [comment]
deleted the fork

**Comment by chriscamacho** [comment]
Transfered it to you, feel free to contact me if you have issues with it (see profile for contact)

**Pull request merged**
